clone:
  depth: 1
cache:
  mount:
    - node_modules
    - experiment/node_modules
    - app/bower_components
build:
  image: crhym3/ci-image
  environment:
    - GAE_SDK_URL=https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.28.zip
  commands:
    # install dependencies
    - npm -q install
    - cd app && ../node_modules/bower/bin/bower install -q --allow-root && cd ..
    - gulp godeps
    # ensure the build works
    - gulp
    # backend testing
    - gulp backend:test
    - curl -sSLo sdk.zip $GAE_SDK_URL && unzip -q sdk.zip
    - go_appengine/goapp test ./backend
deploy:
  bash:
    when:
      owner: GoogleChrome
      branch: master
    script:
      - util/auto-deploy
