sudo: false
language: node
env:
  - GOPATH=$HOME/go
cache:
  directories:
    - node_modules
    - experiment/node_modules
    - app/bower_components
install:
  - mkdir $HOME/go
  - . util/gcloud-install && install_or_update_gcloud
  - npm install -q
  - npm install -g gulp
  - gulp bower
  - gulp godeps
script:
  - gulp
  - gulp backend:test
  - gulp backend:test --gae

