application: io-webapp
version: 1
runtime: python27
api_version: 1
threadsafe: yes

#default_expiration: "0s"

handlers:

- url: /fonts
  static_dir: fonts
  http_headers:
    Access-Control-Allow-Origin: "*"

- url: /images
  static_dir: images
  http_headers:
    Access-Control-Allow-Origin: "*"

- url: /styles
  static_dir: styles
  http_headers:
    Access-Control-Allow-Origin: "*"

- url: /scripts
  static_dir: scripts
  http_headers:
    Access-Control-Allow-Origin: "*"

- url: /temporary_api
  static_dir: temporary_api
  http_headers:
    Access-Control-Allow-Origin: "*"

- url: /$
  static_files: index.html
  upload: index\.html
  http_headers:
    Access-Control-Allow-Origin: "*"
  secure: always

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^(.*/)?node_modules/.*
- ^.*.LICENSE
